### PR TITLE
Add allow_unsafe_types args to StreamingCOCO

### PR DESCRIPTION
**Pull request by karan6181**
## Description of changes:
- The COCO dataset conversion script uses pickle data format for [bounding boxes](https://github.com/mosaicml/streaming/blob/main/streaming/vision/convert/coco.py#L205-L206). Hence, we need an arg `allow_unsafe_types` to the downstream class (StreamingCOCO) to allow iteration.

## Issue #, if available:
https://github.com/mosaicml/streaming/issues/567

## Merge Checklist:
_Put an `x` without space in the boxes that apply. If you are unsure about any checklist, please don't hesitate to ask. We are here to help! This is simply a reminder of what we are going to look for before merging your pull request._

### General
- [x] I have read the [contributor guidelines](https://github.com/mosaicml/streaming/blob/main/CONTRIBUTING.md)
- [ ] This is a documentation change or typo fix. If so, skip the rest of this checklist.
- [x] I certify that the changes I am introducing will be backward compatible, and I have discussed concerns about this, if any, with the MosaicML team.
- [ ] I have updated any necessary documentation, including [README](https://github.com/mosaicml/streaming/blob/main/README.md) and [API docs](https://github.com/mosaicml/streaming/tree/main/docs) (if appropriate).

### Tests
- [x] I ran `pre-commit` on my change. (check out the `pre-commit` section of [prerequisites](https://github.com/mosaicml/streaming/blob/main/CONTRIBUTING.md#prerequisites))
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate).
- [x] I ran the tests locally to make sure it pass. (check out [testing](https://github.com/mosaicml/streaming/blob/main/CONTRIBUTING.md#submitting-a-contribution))
- [ ] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes.

### CODE REVIEW

**Comment by snarayan21** [comment]
regarding @knighton's suggestion that bounding boxes should be floats, are we going to modify this to use non-pickleable type, or go with this PR? @karan6181

**Comment by knighton** [comment]
was originally not pickled

```
   def decode_img(self, data: bytes) -> Image.Image:
        return Image.open(BytesIO(data)).convert('RGB')

    def decode_img_id(self, data: bytes) -> np.int64:
        return np.frombuffer(data, np.int64)[0]

    def decode_htot(self, data: bytes) -> np.int64:
        return np.frombuffer(data, np.int64)[0]

    def decode_wtot(self, data: bytes) -> np.int64:
        return np.frombuffer(data, np.int64)[0]

    def decode_bbox_sizes(self, data: bytes) -> torch.Tensor:
        arr = np.frombuffer(data, np.float32)
        arr = arr.reshape(-1, 4)
        return torch.tensor(arr)

    def decode_bbox_labels(self, data: bytes) -> torch.Tensor:
        arr = np.frombuffer(data, np.int64)
        return torch.tensor(arr)
    ````

**Comment by snarayan21** [comment]
@karan6181 mind updating the PR to use non-pickled datatypes (float)? If you want I can do it

**Comment by snarayan21** [comment]
See #647 instead!

**Pull request closed without merging**
