### PR TITLE
Lazily instantiate the worker barrier in __iter__ (so it all pickles).

### PR DESCRIPTION
**Pull request by knighton**
## Merge Checklist:
_Put an `x` without space in the boxes that apply. If you are unsure about any checklist, please don't hesitate to ask. We are here to help! This is simply a reminder of what we are going to look for before merging your pull request._

### General
- [ ] I have read the [contributor guidelines](https://github.com/mosaicml/streaming/blob/main/CONTRIBUTING.md)
- [ ] This is a documentation change or typo fix. If so, skip the rest of this checklist.
- [ ] I certify that the changes I am introducing will be backward compatible, and I have discussed concerns about this, if any, with the MosaicML team.
- [ ] I have updated any necessary documentation, including [README](https://github.com/mosaicml/streaming/blob/main/README.md) and [API docs](https://github.com/mosaicml/streaming/tree/main/docs) (if appropriate).

### Tests
- [ ] I ran `pre-commit` on my change. (check out the `pre-commit` section of [prerequisites](https://github.com/mosaicml/streaming/blob/main/CONTRIBUTING.md#prerequisites))
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate).
- [ ] I ran the tests locally to make sure it pass. (check out [testing](https://github.com/mosaicml/streaming/blob/main/CONTRIBUTING.md#running-tests))
- [ ] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes.

### CODE REVIEW

**Review by dakinggg — APPROVED** [review]
LGTM

**Review by dakinggg — CHANGES_REQUESTED** [review]
Blocking due to hanging issue, discussing offline

**Review by dakinggg — COMMENTED** [review]
Remove request changes to unblock if needed

**Review by dakinggg — APPROVED** [review]
didn't work

**Comment by dakinggg** [comment]
cc @karan6181 I believe this PR now works. Tested a simple training script on both mac and linux. pytest passes on both mac and a GPU instance. not sure if there is other stuff y'all would want to test. But you should be able to remove the fork thing once this PR is merged

**Comment by karan6181** [comment]
Changes looks good to me. Can one of you (@dakinggg , @knighton) also remove the method `tests_setup_and_teardown()` from `tests/conftest.py` since we don't need it anymore. Thanks!

**Review by karan6181 — APPROVED** [review]

**Pull request merged**
